spring.application.name=pichakService
#============================= SERVER =======================================
server.port=8082
tcp.server.port=8001
tcp.service.timeout=900000
service.name=aaa_server
service.id=1
iso.key=F200B1E948D327B5
unhandeled.exception=-99999999
spring.jackson.default-property-inclusion=NON_NULL
debug=true
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
queue.request.timeout=60000
vekalati.deposit.type.list=JARI_ACCOUNT,PASANDAZ,SHORT_ACCOUNT,SPECIAL_SHORT_ACCOUNT,ANDOKHTE_ACCOUNT
#============================= DATABASE =======================================
#spring.datasource.url=jdbc:h2:~/pichak2-db-test
#spring.jpa.defer-datasource-initialization=true
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
#spring.jpa.properties.hibernate.connection.CharSet=utf-8
#spring.jpa.properties.hibernate.connection.useUnicode=true
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.hikari.maximum-pool-size=100
#spring.datasource.maxActive=100
# Enabling H2 Console
#spring.h2.console.enabled=true
# Custom H2 Console URL
#spring.h2.console.=/h2
#spring.h2.console.settings.web-allow-others=true
#============================= SECURITY =======================================
spring.main.allow-bean-definition-overriding=true
#security.signing-key=qazQAZMaYzkSjmkzPC57L123321
#security.encoding-strength=256
#security.security-realm=AAA SERVER Realm
#security.security-max_attempt=6
#security.security-max_request_attempt=100
#security.security-max_request_time=60000
#security.security-max_request_loop_time=*/10 * * * * ?
access-control-allow-origin=*
#trust.store.password=123!@#
server.ssl.enabled=false
#server.ssl.enabled-protocols=TLSv1.2+TLSv1.3
#server.ssl.key-store=classpath:keystore/pichak.pfx
#server.ssl.key-store-password=1qaz!QAZ
#server.ssl.keyStoreType=PKCS12

#socket.ssl.enabled=false
#socket.ssl.trust-store=
#socket.ssl.trust-store-password=
#socket.ssl.trust-store-type=PKCS12
#============================= LOG =======================================
#logging.level.root=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#============================= CHANNEL =======================================
#TAMARTASH
SOFTWARE_AGENT_USER=omni
SOFTWARE_AGENT_PASS=48612029
#gateway.spi.jms.provider.url= t3://192.168.251.117:7001
#gateway.spi.jms.message.selector=m-t143-211
CASPIAN_CM_HOST=192.168.105.143
#gateway.spi.jms.requestQueue=com.casp.jms.queue.ChannelManagerRequest
#gateway.spi.jms.responseQueue=com.casp.jms.queue.ChannelManagerResponse
#LIVE
#SOFTWARE_AGENT_USER=omni
#SOFTWARE_AGENT_PASS=37122729
#gateway.spi.jms.provider.url=t3://192.168.247.171:7001
#gateway.spi.jms.message.selector=sel192168247171
#CASPIAN_CM_HOST=192.168.18.117

#LIVE PICHAK
#SOFTWARE_AGENT_USER=omni
#SOFTWARE_AGENT_PASS=37122729
#gateway.spi.jms.provider.url=t3://192.168.247.222:7001
#gateway.spi.jms.message.selector=sel192168247222
#CASPIAN_CM_HOST=192.168.247.222

#PRELIVE
#SOFTWARE_AGENT_USER=omni
#SOFTWARE_AGENT_PASS=48612029
#gateway.spi.jms.provider.url=t3://192.168.17.95:7001
#gateway.spi.jms.message.selector=sel1921681795_JAFAR
#CASPIAN_CM_HOST=192.168.17.95
#gateway.spi.jms.channel.name=PERSONAL_INTERNET_BANK


#PRELIVE-OMNI
#SOFTWARE_AGENT_USER=omni
#SOFTWARE_AGENT_PASS=32635750
#gateway.spi.jms.provider.url=t3://192.168.250.71:7001
##gateway.spi.jms.message.selector=sel19216825071
#gateway.spi.jms.message.selector=sel19216825071_parsiness
#CASPIAN_CM_HOST=192.168.250.71
#

#gateway.spi.jms.requestQueue=com.casp.jms.queue.InternalChannelManagerRequest
#gateway.spi.jms.responseQueue=com.casp.jms.queue.InternalChannelManagerResponse
##APPTEST
#gateway.spi.jms.provider.url=t3://192.168.251.120:7001
#gateway.spi.jms.message.selector=sel19216818120
#CASPIAN_CM_HOST=192.168.251.117
#CASPIAN_CM_PORT=7001
#gateway.spi.jms.channel.name=SOFTWARE_AGENT
#gateway.spi.jms.provider.url=t3://192.168.18.120:7001
#gateway.spi.jms.message.selector=sel19216818120
#CASPIAN_CM_HOST=192.168.18.120
#gateway.spi.jms.message.selector:CHM-Server-143
#CASPIAN_CM_HOST:192.168.105.160
#gateway.spi.jms.message.selector=tamartash
#gateway.spi.jms.provider.url=t3://192.168.18.117:7001
#gateway.spi.jms.channel.name=MOBILE_BANK
#gateway.spi.jms.requestQueue=com.casp.jms.queue.ChannelManagerRequest
#gateway.spi.jms.responseQueue=com.casp.jms.queue.ChannelManagerResponse
#gateway.spi.jms.channel.name=PERSONAL_INTERNET_BANK
#caspian.chm.sso=false
gateway.spi.profile=JMS
ENVIRONMENT_SPI_KEY_STORE_PASS=123456
ENVIRONMENT_SPI_TRUST_STORE_LOCATION=/home/cacerts.jks
CASPIAN_SPI_SSL_ENABLED=true
#============================= LOTUS =======================================
lotus.core.channel=BRANCH
lotus.core.connectionFactory=com.casp.jms.mainConnectionFactory
#lotus.core.filter=ServerNode-UAT
#lotus.core.request.queue=com.casp.jms.queue.LotusQueueRequest
#lotus.core.response.queue=com.casp.jms.queue.LotusQueueResponse
#spl.lotus.core.request.queue=com.casp.jms.queue.SandboxQueueRequest
#spl.lotus.core.response.queue=com.casp.jms.queue.SandboxQueueResponse
lotus.core.version=1.3.16.0
lotus.weblogic.url=t3://192.168.251.117:7001
#lotus.weblogic.url=t3://apptest-weblogic.caspian.com:7001
#lotus.core.filter=ServerNode-Saeed
lotus.core.filter=Yazdian-Lotus
#lotus.core.filter=ServerNode-APPTEST
#lotus.core.filter=ServerNode-OMNI
#lotus.core.request.queue=com.casp.jms.queue.LotusQueueRequest-omni
#lotus.core.response.queue=com.casp.jms.queue.LotusQueueResponse-omni
#lotus.core.username=hdreza@5010:IRR
#lotus.core.branchcode=1002
#lotus.weblogic.url=t3://192.168.250.12:7001
#lotus.core.filter=ServerNode-PRELIVE
#lotus.core.filter=ServerNode-Taherkhani
#lotus.core.request.queue=com.casp.jms.queue.LotusQueueRequest
#lotus.core.response.queue=com.casp.jms.queue.LotusQueueResponse
lotus.core.username=hdreza
lotus.core.branchcode=5010
#lotus.core.filter=ServerNode-PRELIVE
#lotus.core.request.queue=com.casp.jms.queue.LotusQueueRequest
#lotus.core.response.queue=com.casp.jms.queue.LotusQueueResponse
#lotus.weblogic.url=t3://192.168.250.12:7001
#lotus.core.filter=ServerNode-Sheikhvand1
lotus.core.request.queue=com.casp.jms.queue.SandboxQueueRequest
lotus.core.response.queue=com.casp.jms.queue.SandboxQueueResponse
#lotus.weblogic.url=t3://192.168.18.117:7001
#lotus.core.username=hdreza@5010:IRR
lotus.core.queue.request.timeout=600000
#lotus.core.branchcode=1002
#============================= SHAHKAR =======================================
shahkar.url=http://192.168.243.69:8085/api/shahkar/ServiceIDmatching
shahkar.identificationType=0
shahkar.serviceType=2
shahkar.header.authorization=Basic aHVzc2VpbmlAY2FzcGNvLmlyOlVpMTg3IQ==
#============================= TOTP =======================================
otp.pre.text=\u06A9\u062F \u06CC\u06A9\u0628\u0627\u0631 \u0645\u0635\u0631\u0641
otp.post.text=\u0633\u0627\u0645\u0627\u0646\u0647 \u067E\u06CC\u0686\u06A9
otp.post.vekalati=\u0633\u0627\u0645\u0627\u0646\u0647\u0020\u0648\u06a9\u0627\u0644\u062a\u06cc\u0020\u0628\u0627\u0646\u06a9\u0020\u067e\u0627\u0631\u0633\u06cc\u0627\u0646
otp.post.pichak=\u0633\u0627\u0645\u0627\u0646\u0647\u0020\u067e\u06cc\u0686\u06a9\u0020\u0628\u0627\u0646\u06a9\u0020\u067e\u0627\u0631\u0633\u06cc\u0627\u0646
otp.dto.otpValidTime=180000
otp.dto.returnDigit=5
spring.messages.encoding=UTF-8
#============================= EXCEPTION =======================================
error.code.null=\u062E\u0637\u0627\u06CC \u0639\u0645\u0648\u0645\u06CC \u0631\u062E \u062F\u0627\u062F\u0647 \u0627\u0633\u062A
error.code.latin=false


gateway.spi.jms.provider.url=t3://192.168.251.117:7001
#gateway.spi.jms.provider.url = t3://apptest-weblogic.caspian.com:7001
#gateway.spi.jms.requestQueue=com.casp.jms.queue.LotusQueueRequest
#gateway.spi.jms.responseQueue=com.casp.jms.queue.LotusQueueResponse
gateway.spi.jms.message.selector = sel19216818120

gateway.spi.jms.factory.initial=weblogic.jndi.WLInitialContextFactory
gateway.spi.jms.channel.name=MOBILE_BANK
gateway.spi.jms.connectionFactory=com.casp.jms.mainConnectionFactory
gateway.spi.jms.requestQueue=com.casp.jms.queue.SandboxQueueRequest
gateway.spi.jms.responseQueue=com.casp.jms.queue.SandboxQueueResponse
gateway.spi.jms.delivery.mode=1
gateway.spi.jms.concurrentConsumers=11
gateway.spi.jms.message.ttl=5000
gateway.spi.jms.channel.format=object/java


lotus.core.weblogic.url=t3://192.168.251.117:7001
lotus.core.cryptography.lotus.host.alias=lotus-host
lotus.core.default.user=hdreza
lotus.core.default.branchcode=5010
lotus.core.default.currency=IRR
lotus.core.default.channel=BRANCH   

security.local-jwt.secret=3apyd5JMX4yfGtgEsey5JQU2mbzHuEPDb0u2GoXayDK
security.local-jwt.expiration-ms=360000