tcp.server.port=8001

lotus.core.channel=BRANCH
lotus.core.connectionFactory=com.casp.jms.mainConnectionFactory
lotus.weblogic.url=t3://192.168.251.117:7001
lotus.core.request.queue=com.casp.jms.queue.SandboxQueueRequest
lotus.core.response.queue=com.casp.jms.queue.SandboxQueueResponse
lotus.core.filter=Yazdian-Lotus
spring.datasource.url=jdbc:h2:~/pichak2-db-test2

gateway.spi.jms.provider.url=t3://192.168.251.117:7001
gateway.spi.jms.message.selector = sel19216818120
gateway.spi.jms.requestQueue=com.casp.jms.queue.SandboxQueueRequest
gateway.spi.jms.responseQueue=com.casp.jms.queue.SandboxQueueResponse