tcp.server.port=8001

#lotus.core.channel=BRANCH
lotus.core.filter=Yazdian-Lotus


gateway.spi.jms.provider.url=t3://192.168.251.117:7001
gateway.spi.jms.message.selector = sel19216818120
gateway.spi.jms.requestQueue=com.casp.jms.queue.SandboxQueueRequest
gateway.spi.jms.responseQueue=com.casp.jms.queue.SandboxQueueResponse